### ISSUE TITLE
Add customizable variable for pointing at alternative LanguageServer.jl environment

### ISSUE THREAD

**Issue by non-Jedi** [non-Jedi/eglot-jl#13]
Per request from Zac.

Would help me with development on the actual language server as well.

**Comment by ffevotte** [comment]
Do you need help with this? I should have some time to propose a PR tonight

**Comment by non-Jedi** [comment]
Nah. I should be able to get to this relatively soon. Just opening an issue to make sure I don't lose track of it. Thanks though! I really appreciate your help with this package and hope to get time to review #12 in the next few days.

**Comment by ffevotte** [comment]
Take your time for #12, there's no need to rush!

And don't hesitate to ask for help (I guess one of the benefits of being locked down is that it gives some time to code!)
