### ISSUE TITLE
Managing several Julia versions

### ISSUE THREAD

**Issue by mkschleg** [non-Jedi/eglot-jl#17]
Is there a way for me to target specific julia versions (i.e. pointing to different executables say in the local directory variables)? For instance, some of my projects require Julia 1.3 and some require 1.4 (to be compatible w/ an environment I have no control over), but I also want to play with 1.5 in some personal projects.

Any pointers for where to put this for a pull request if not?

**Comment by non-Jedi** [comment]
Does customizing `eglot-jl-julia-command` not work for your use-case?
