### ISSUE TITLE
Timeout error even with successful Symbol Server

### ISSUE THREAD

**Issue by mkschleg** [non-Jedi/eglot-jl#2]
emacs: v26.3
eglot: 20200113.1722
eglot-jl: 20200120.1457

I'm having some issues w/ eglot connecting to the server. The eglot stderr shows the symbol server succeeding (i.e. `[ Info: store set` being printed), but when trying to run eglot commands the following error is returned:

`jsonrpc-error: jsonrpc-error: "No current JSON-RPC connection", (jsonrpc-error-code . 32603), (jsonrpc-error-message . "No current JSON-RPC connection")`

Then after the usual timeout time the server times out. I've included the output, event logs, and the end of the stderr log bellow:

**output**

```julia
Activating environment at `~/.emacs.d/elpa/eglot-jl-20200120.1457/Project.toml`
Content-Length: 855

{"id":1,"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":["."]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":false,"implementationProvider":false,"referencesProvider":true,"documentHighlightProvider":false,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":false,"codeLensProvider":null,"documentFormattingProvider":true,"documentRangeFormattingProvider":false,"documentOnTypeFormattingProvider":null,"renameProvider":true,"documentLinkProvider":null,"colorProvider":false,"foldingRangeProvider":false,"declarationProvider":false,"executeCommandProvider":null,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}},"experimental":null}}}
```

**events**

```lisp
client-request (id:1) Mon Jan 20 20:27:46 2020:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
	  (:processId 54072 :rootPath "/Users/Matt/Documents/Developer_Projects/juliaDev/RLCore/" :rootUri "file:///Users/Matt/Documents/Developer_Projects/juliaDev/RLCore/" :initializationOptions nil :capabilities
		      (:workspace
		       (:applyEdit t :executeCommand
				   (:dynamicRegistration :json-false)
				   :workspaceEdit
				   (:documentChanges :json-false)
				   :didChangeWatchedFiles
				   (:dynamicRegistration t)
				   :symbol
				   (:dynamicRegistration :json-false)
				   :configuration t)
		       :textDocument
		       (:synchronization
			(:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
			:completion
			(:dynamicRegistration :json-false :completionItem
					      (:snippetSupport :json-false)
					      :contextSupport t)
			:hover
			(:dynamicRegistration :json-false :contentFormat
					      ["markdown" "plaintext"])
			:signatureHelp
			(:dynamicRegistration :json-false :signatureInformation
					      (:parameterInformation
					       (:labelOffsetSupport t)))
			:references
			(:dynamicRegistration :json-false)
			:definition
			(:dynamicRegistration :json-false)
			:declaration
			(:dynamicRegistration :json-false)
			:implementation
			(:dynamicRegistration :json-false)
			:typeDefinition
			(:dynamicRegistration :json-false)
			:documentSymbol
			(:dynamicRegistration :json-false :symbolKind
					      (:valueSet
					       [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
			:documentHighlight
			(:dynamicRegistration :json-false)
			:codeAction
			(:dynamicRegistration :json-false :codeActionLiteralSupport
					      (:codeActionKind
					       (:valueSet
						["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"])))
			:formatting
			(:dynamicRegistration :json-false)
			:rangeFormatting
			(:dynamicRegistration :json-false)
			:rename
			(:dynamicRegistration :json-false)
			:publishDiagnostics
			(:relatedInformation :json-false))
		       :experimental nil)))

internal Mon Jan 20 20:28:46 2020:
(:message "Connection state changed" :change "killed: 9\n")


----------b---y---e---b---y---e----------

```

**stderr**
```julia
...
[ Info: loading dependency StatsFuns
[ Info: loading dependency Rmath
[ Info: loading dependency MacroTools
[ Info: loading dependency CSTParser
[ Info: Tried to load CSTParser cache as a dependency but failed.
[ Info: loading dependency Tokenize
[ Info: Tried to load Tokenize cache as a dependency but failed.
[ Info: store set

Process EGLOT (RLCore/julia-mode) stderr finished
```

**Comment by non-Jedi** [comment]
The language server doesn't seem to be responding to the `initialize` request from eglot; might be the language server compiling the method needed to reply. Could you try bumping up the value of `eglot-connect-timeout` to see if this works itself out with more time?

**Comment by mkschleg** [comment]
I've bumped eglot-connect-timeout to 300 seconds, but see the same behavior. Is there any other output that I'm unaware of that would be useful to debug this? Or maybe a way to see what language server is doing w/ the message, like a verbose mode?

**Comment by non-Jedi** [comment]
Changing `false` to `true` in [the invocation of the language server](https://github.com/non-Jedi/eglot-jl/blob/master/eglot-jl.jl#L12) turns on debug output which will show up in stderr, but I'm skeptical it will show anything helpful. Worth a shot though.

**Comment by mkschleg** [comment]
Hmm. You're right. The Language server seems to receive the `initialize` request. And sends the results back. I'm assuming these responses back and forth are dictionaries?

```julia
[ Info: loading dependency Dictionaries
[ Info: store set
[ Info: RECEIVED: {"jsonrpc":"2.0","id":1,"method":"initialize","params":{"processId":54072,"rootPath":"/Users/Matt/Documents/Research/projects/DeepRL.jl/","rootUri":"file:///Users/Matt/Documents/Research/projects/DeepRL.jl/","initializationOptions":null,"capabilities":{"workspace":{"applyEdit":true,"executeCommand":{"dynamicRegistration":false},"workspaceEdit":{"documentChanges":false},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":false},"configuration":true},"textDocument":{"synchronization":{"dynamicRegistration":false,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":false,"completionItem":{"snippetSupport":false},"contextSupport":true},"hover":{"dynamicRegistration":false,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":false,"signatureInformation":{"parameterInformation":{"labelOffsetSupport":true}}},"references":{"dynamicRegistration":false},"definition":{"dynamicRegistration":false},"declaration":{"dynamicRegistration":false},"implementation":{"dynamicRegistration":false},"typeDefinition":{"dynamicRegistration":false},"documentSymbol":{"dynamicRegistration":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"documentHighlight":{"dynamicRegistration":false},"codeAction":{"dynamicRegistration":false,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"formatting":{"dynamicRegistration":false},"rangeFormatting":{"dynamicRegistration":false},"rename":{"dynamicRegistration":false},"publishDiagnostics":{"relatedInformation":false}},"experimental":null}}}
[ Info: 
[ Info: SENT: {"id":1,"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":["."]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":false,"implementationProvider":false,"referencesProvider":true,"documentHighlightProvider":false,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":false,"codeLensProvider":null,"documentFormattingProvider":true,"documentRangeFormattingProvider":false,"documentOnTypeFormattingProvider":null,"renameProvider":true,"documentLinkProvider":null,"colorProvider":false,"foldingRangeProvider":false,"declarationProvider":false,"executeCommandProvider":null,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}},"experimental":null}}}
[ Info: TIME:1.5

Process EGLOT (DeepRL/julia-mode) stderr finished
```

**Comment by non-Jedi** [comment]
The next step in troubleshooting is to see if you can get one of [the out-of-the-box language servers](https://github.com/joaotavora/eglot#connecting-to-a-server) working with eglot.

Just for reference, eglot works by sending JSON-RPC back and forth over unix pipes. It seems the pipe from eglot to the language server is working, but the pipe back from language server to eglot seems broken. I've wished several times for a test-harness to run language servers in, but the only things approximating that is exclusive to language servers built using Microsoft's JS framework.

**Comment by mkschleg** [comment]
The eglot backend for python (using pls) is working.

**Comment by non-Jedi** [comment]
It looks like you've tried this with multiple repositories and gotten the same effect?

**Comment by mkschleg** [comment]
Yeah. I've even tried this on a very simple repository (i.e. very few packages installed).

**Comment by mkschleg** [comment]
I'm running this with MacOS Catalina.

**Comment by non-Jedi** [comment]
I haven't tested on a Mac, and don't have access to do so. :/ What version of jsonrpc are you on?

**Comment by non-Jedi** [comment]
I think I found the problem. [According to the LSP spec, the `Content-Length` header must be terminated by 2 `\r\n`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#headerPart). Can you confirm that in the output buffer, there's only `\n\n` between the `Content-Length` header and the JSON rpc rather than `\r\n\r\n` as per the spec?

**Comment by mkschleg** [comment]
Hmmm. I think that is just github stripping the carriage returns. With whitespace mode on in emacs I see
```
Content-Length: 855^M$
^M$
```

**Comment by mkschleg** [comment]
And I'm on jsonrpc v1.0.9

**Comment by non-Jedi** [comment]
So here's what I know now after having looked at this in more depth:

- eglot sends a request to the language server
- the language server replies
- The reply of the language server is reflected in the output buffer and seems to be proper JSON rpc
- `jsonrpc--process-filter` never recognizes the message as a reply (I'm not sure why the handling for the `Content-Length` headers is in `jsonrpc` instead of `eglot` since that detail is specific to LSP and not part of the JSON RPC spec).

I believe this is an upstream bug with eglot or jsonrpc. Please file an issue at the eglot repo linking back to this one. It's probably a problem with the regexp `"\\(?:.*: .*\r\n\\)*Content-Length: \
*\\([[:digit:]]+\\)\r\n\\(?:.*: .*\r\n\\)*\r\n"` in `jsonrpc--process-filter`, but I'm absolutely atrocious at regexps. No idea why it would trigger on osx but not linux; line-endings are the same on both platforms.

**Comment by mkschleg** [comment]
After waiting a few months, things seem to be working now on 1.4. Not sure what has changed, but going to close.

**Comment by non-Jedi** [comment]
Glad it's working for you now. :)
