### ISSUE TITLE
Need to force "eglot-jl-depot"?

### ISSUE THREAD

**Issue by xgqt** [non-Jedi/eglot-jl#24]
I'm getting following warnings from eglot:

```
...
 (:range
  (:start
  (:line 21 :character 9)
   :end
   (:line 21 :character 18))
   :severity 2 :code "Julia" :source "Julia" :message "Missing reference: GtkButton")
 (:range
  (:start
  (:line 24 :character 0)
  :end
 (:line 24 :character 14))
 :severity 2 :code "Julia" :source "Julia" :message "Missing reference: signal_connect")
 ...
 ```
 The file in question: https://gitlab.com/xgqt/gtkdemos/-/blob/master/GTK3/julia/helloworld/HelloworldGtk.jl
 Running the file from terminal works (as I have "Gtk" package dependency installed).

**Comment by xgqt** [comment]
Ok, I see the problem, Eglot-Jl uses the wrong depot path, my depot path is:
![image](https://user-images.githubusercontent.com/47485207/126721167-d8418111-b5d5-4f1d-ae0f-1c4322a3ebdf.png)


After I exported `JULIA_DEPOT_PATH=~/.julia` and installed Gtk the warnings are gone, so Eglot-Jl picked wrong depot path

**Comment by xgqt** [comment]
After forcing `eglot-jl-depot` to be set to my `JULIA_DEPOT_PATH` it appears t work
```
:config (setq eglot-jl-depot (getenv "JULIA_DEPOT_PATH"))
```
If this is not a bug then docs are misleading https://github.com/non-Jedi/eglot-jl/blob/master/eglot-jl.el#L54

**Comment by non-Jedi** [comment]
Just pushed a commit that should fix this. Sorry about the long delay in replying.
