### ISSUE TITLE
Explanation of whats going on under the hood

### ISSUE THREAD

**Issue by reachtarunhere** [non-Jedi/eglot-jl#26]
Hi! Thanks for the awesome project. I have got it working.

I am confused about one item:

Do I need to install the language and symbolserver for each enviorment/project I do with a .toml file?

If I use the default env I get a lot of linting issues when using packages that are not part of the default env.

Is there some way to signal the language server to change the env after it is running?

Thanks

**Comment by non-Jedi** [comment]
The language server will automatically be installed into its own environment by eglot-jl; no action is required by you to install.

When you invoke `eglot` in a julia buffer, emacs recursively searches upward from the julia file's directory trying to find a Project.toml or JuliaProject.toml which is used for completion and linting purposes. Afterward, all files that are children of that project dir can make use of the language server that's started.

LanguageServer.jl does provide a way to switch the project of an already running language server, but we are not hooked up to it. Instead, if you invoke `eglot` in a file which isn't part of a project for which there's already a language server started, a new language server will spin up.
