### ISSUE TITLE
 No such file or directory, vterm-module

### ISSUE THREAD

**Issue by StefanPofahl** [non-Jedi/eglot-jl#32]
Is there any experience how to install / use eglot-jl on MS Windows?
I followed the snippet of the init.el given in the [Julia-Forum](https://discourse.julialang.org/t/using-languageserver-jl-with-eglot-in-emacs/23125/80)
I did the following:
1.) Installed inside emacs:
;;  a.) yasnippet
;;  b.) vterm
;;  c.) vterm-module
And made sure that following application are in the search-path (%PATH%):
a.) cmake
b.) sh

But the compilation of `vterm` fails. :-(
See also my question here:
https://answers.launchpad.net/libvterm/+question/704002

**Comment by non-Jedi** [comment]
Hi Stefan Pofahl. The error you're seeing is for vterm which is completely unrelated to eglot. The [instructions shown at the top of the README](https://github.com/non-Jedi/eglot-jl#eglot-jl) should work on Windows just as well as other platforms. If you have issues with that installation method, please open a new issue.

If it's helpful, here is the `use-package` based snippet from discourse with only the eglot-related stuff included:

```elisp
(use-package julia-mode
    :mode "\\.jl\\'"
    :config
    (add-hook 'julia-mode-hook 'eglot-jl-init)
    (add-hook 'julia-mode-hook 'eglot-ensure)
    (add-hook 'julia-mode-hook (lambda () (setq eglot-connect-timeout 120)))
    (add-hook 'julia-mode-hook (lambda () (setq eglot-autoshutdown t))))
```

I don't use `use-package` myself, so I may have gotten this subtly wrong, but I believe that should work.

**Comment by non-Jedi** [comment]
The most important parts of that snippet could be done manually by using `<kbd>M-x</kbd> eglot-jl-init` followed by `<kbd>M-x</kbd> eglot` after opening a julia file in the current buffer.
