### ISSUE TITLE
Flycheck causes max-lisp-eval-depth error

### ISSUE THREAD

**Issue by TS-CUBED** [non-Jedi/eglot-jl#35]
I am using eglot-jl in doom emacs. Eglot-jl itself is running fine, but when I activate flycheck (which uses eglot):

```
First checker to run:

  eglot
    - may enable: yes
    - may run:    t

Flycheck Mode is enabled. Use SPC u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 32snapshot
Emacs version:    28.1
System:           x86_64-pc-linux-gnu
Window system:    x
```

I get the error:

```
Error while checking syntax automatically: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
```

Is this an issue with eglot-jl or flycheck?

## Steps to reproduce
1. Using Doom Emacs
2. In `init.el` activate `(syntax)` to enable flycheck, activate `(lsp +eglot)` to get eglot, and `(julia +lsp)` to get eglot-jl
3. Open Julia file and wait for eglot-jl to initialise
4. Error occurs: `Error while checking syntax automatically: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")`

**Comment by TS-CUBED** [comment]
Problem seems to be with flycheck-eglot in Doom Emacs, so raised the issue there as well.

https://github.com/doomemacs/doomemacs/issues/7034

**Comment by non-Jedi** [comment]
Quick search through the doom repo's issue suggests that this isn't isolated to just Julia: https://github.com/doomemacs/doomemacs/issues/6466.

**Comment by TS-CUBED** [comment]
Thanks. It seems that moving to `flymake` is the straightforward solution to this problem.
