### ISSUE TITLE
Cannot find core packages

### ISSUE THREAD

**Issue by warnerwarner** [non-Jedi/eglot-jl#56]
Hi, 

Thanks for this package. Though I'm having trouble trying to get the language server to find core packages from Julia, e.g. Statistics, or even Pkg. I've only found the way around this is to add every package to the Project/Manifest toml. Is that correct way of doing this? Or have I not correctly implemented my project/this plug in.

Thanks

**Comment by non-Jedi** [comment]
Hi @warnerwarner! Yes, the general expectation is that any packages you use in a project will be included in your Project.toml, even standard libraries. Julia won't actually let you `using` or `include` a package that isn't in your `Project.toml` from within a package:

```
shell> tree
.
├── Project.toml
└── src
    └── MyExample.jl

2 directories, 2 files

shell> cat src/MyExample.jl
module MyExample
using Statistics

greet() = print("Hello World!")

end # module MyExample

(MyExample) pkg> st
Project MyExample v0.1.0
Status `~/repos/MyExample/Project.toml` (empty project)

julia> using MyExample
[ Info: Precompiling MyExample [a1bfc844-9669-448b-adaa-dd0e148aa7dc]
ERROR: LoadError: ArgumentError: Package MyExample does not have Statistics in its dependencies:
...(truncated)...
```
